[package]
name = "day11"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "*", features = ["blocking", "json"] }
dotenv = "*"
petgraph = "*"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "criterion"
harness = false
